apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-lqil
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-sgaikwad-tenant/partner-catalog-1/partner-catalog-lqil@sha256:547933d8974bb473020fa6440b73c267a87b9159c6ff20404aa5ba0d18541ddd
        name: my-java-springboot
        resources: {}
status: {}
